version: "3.2"
services:
  server:
    restart: always
    # ports:
    #   - "8080:8080"
    network_mode: host
    build: .
    volumes:
      - type: bind
        source: ./configs/
        target: /configs
    command: /MessengerServer/server --conf "/configs/config.json" --templ "/MessengerServer/registrationForm.html"